### ISSUE TITLE
Search Profiles not displaying results for some profiles - after we included the Filter 'Include those you already follow'

### ISSUE THREAD

**Issue by Dewansahil** [Karma3Labs/ts-eigencaster#2]
<img width="876" alt="Screen Shot 2022-12-24 at 10 53 06 AM" src="https://user-images.githubusercontent.com/45057123/209448171-581b37eb-10cf-43be-86a4-fd26ea847e08.png">

**Comment by astralblue** [comment]
It's due to the way the recommendation works: 1) Take the top N users, and 2) filter out those already followed.  It would happen if the person is already following most of the top N users recommended by EigenTrust, a likely scenario if a user started using EigenTrust for discovering people to follow.

To solve this, I'm going to create a temporary table within a transaction to store the recommendation result, then do a join with the users table.  @pkakelas opinions?
